name: basic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Run tests
      run: |
        cd ring-lwe  # Change to the 'ring-lwe' directory
        cargo build --verbose
        cargo test --verbose
